/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AlgorithmSolution {
  bestDistanceSolution: ProblemSolution
  bestPriceSolution: ProblemSolution
  bestEmptySolution: ProblemSolution
}

export interface Location {
  hash: string
  latitude: number
  longitude: number
}

export interface Order {
  id: number
  pickupLocation: Location
  deliveryLocation: Location
  loadFactor: number
}

export interface Problem {
  vehicles: Array<Vehicle>
  orders: Array<Order>
}

export interface ProblemSolution {
  routes: Record<string, VehicleRoute>
  totalDistance: number
  emptyDistance: number
  totalPrice: number
}

export interface RouteStop {
  orderId: number
  type: string
}

export declare function solveBruteForce(problem: Problem): AlgorithmSolution

export interface Vehicle {
  id: number
  startLocation: Location
  priceKm: number
}

export interface VehicleRoute {
  stops: Array<RouteStop>
  totalDistance: number
  emptyDistance: number
  totalPrice: number
}
