/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AlgorithmSolution {
  bestDistanceSolution: ProblemSolution
  bestPriceSolution: ProblemSolution
  bestEmptySolution: ProblemSolution
}

/**
 * Optional per-call overrides for CEA. Any field left undefined falls back
 * to the WC13 defaults baked into `CeaConfig::default()`.
 */
export interface CeaConfig {
  populationSize?: number
  convCount?: number
  wallTimeCapMs?: number
  recombinationFractionLow?: number
  recombinationFractionHigh?: number
  pReinsertion?: number
  pCrossover?: number
  seed?: number
}

export interface CeaConvergencePoint {
  timeMs: number
  /** Generation index. Same JS-number caveat as PsaConvergencePoint::iteration. */
  generation: number
  totalDistance: number
  emptyDistance: number
  totalPrice: number
}

export interface CeaSolved {
  solution: ProblemSolution
  history: Array<CeaConvergencePoint>
  generations: number
}

export interface Location {
  hash: string
  latitude: number
  longitude: number
}

/**
 * Direct-sum lower bound for all three objectives in one O(N) pass.
 * EMPTY's component is always 0 by construction (see
 * `documents/MILP_adaptation_notes.md`); kept in the result for symmetry
 * with the other two objectives.
 */
export declare function lowerBoundDirect(problem: Problem): LowerBoundsResult

/**
 * LP-relaxation lower bound for one objective. EMPTY is documented as
 * returning the trivial `0` because the implementation's load-aware
 * empty distance is not bound by the §2.4 formula — callers wanting a
 * non-trivial bound on EMPTY should fall through to `lowerBoundDirect`
 * (which also returns 0) and rely on metaheuristic upper bounds.
 */
export declare function lowerBoundLp(problem: Problem, target: string): number

/**
 * Direct-sum bound returned by `lowerBoundDirect`. All three objectives
 * in one O(N) pass (the Rust function returns the same shape).
 */
export interface LowerBoundsResult {
  empty: number
  distance: number
  price: number
}

/**
 * MILP run config. `timeoutMs <= 0` (or undefined) falls back to
 * `vrppd_milp::DEFAULT_TIMEOUT` (30 minutes per PLAN.md §3.3).
 */
export interface MilpConfig {
  timeoutMs?: number
}

/**
 * MILP result. `status` is `"OPTIMAL"` if HiGHS proved `value` is the
 * MILP optimum, `"TIMEDOUT"` if the wall-clock budget expired before
 * optimality was proven (in which case `value` is the best primal
 * incumbent found).
 */
export interface MilpResult {
  value: number
  status: string
  solveTimeMs: number
}

export interface Order {
  id: number
  pickupLocation: Location
  deliveryLocation: Location
  loadFactor: number
}

export interface Problem {
  vehicles: Array<Vehicle>
  orders: Array<Order>
}

export interface ProblemSolution {
  routes: Record<string, VehicleRoute>
  totalDistance: number
  emptyDistance: number
  totalPrice: number
}

/**
 * Optional per-call overrides matching the TS `SimulatedAnnealingConfig` plus
 * the multi-thread pipeline parameters. Any field left undefined falls back
 * to the per-objective tuned default.
 */
export interface PsaConfig {
  initialTemp?: number
  coolingRate?: number
  minTemp?: number
  maxIterations?: number
  seed?: number
  threads?: number
  batchSize?: number
  syncInterval?: number
  reheatFloor?: number
  weightShift?: number
  weightSwap?: number
  weightShuffle?: number
}

export interface PsaConvergencePoint {
  timeMs: number
  /**
   * Iteration index. JS receives a `number`; iterations stay well within
   * `Number.MAX_SAFE_INTEGER` for any plausible run length.
   */
  iteration: number
  totalDistance: number
  emptyDistance: number
  totalPrice: number
}

export interface PsaSolved {
  solution: ProblemSolution
  history: Array<PsaConvergencePoint>
}

export interface RouteStop {
  orderId: number
  type: string
}

export declare function solveBruteForce(problem: Problem): AlgorithmSolution

/**
 * Run the Coevolutionary Algorithm. `target` accepts the same strings as
 * `solve_p_sa`. `config.seed` (if provided) gives a reproducible run.
 */
export declare function solveCea(problem: Problem, target: string, config?: CeaConfig | undefined | null): CeaSolved

/**
 * Exact MILP via the bundled HiGHS solver. `target` accepts the same
 * strings as the metaheuristic bindings; `EMPTY` is rejected because
 * the MILP formulation models a different EMPTY than the
 * implementation (see `documents/MILP_adaptation_notes.md`).
 */
export declare function solveMilp(problem: Problem, target: string, config?: MilpConfig | undefined | null): MilpResult

/**
 * Run the multi-thread p-SA pipeline. `target` accepts the same SCREAMING_CASE
 * strings as the TS `OptimizationTarget` enum: "EMPTY", "DISTANCE", "PRICE".
 */
export declare function solvePSa(problem: Problem, target: string, config?: PsaConfig | undefined | null): PsaSolved

export interface Vehicle {
  id: number
  startLocation: Location
  priceKm: number
}

export interface VehicleRoute {
  stops: Array<RouteStop>
  totalDistance: number
  emptyDistance: number
  totalPrice: number
}
